
spring:

  # spring-datasource
  datasource:
    url: jdbc:mysql://localhost:13005/x?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false&sessionVariables=sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
    username: x
    password: x


server:
  ip: 0.0.0.0
  port: 54000
